name: ACR122U NFC Reader
version: "1.2.1"
slug: acr122u_reader
description: ACR122U reader with native tags, entities, and device triggers
url: https://github.com/Flaniel44/ha-usb-nfc
startup: services
boot: auto
init: false
arch:
  - aarch64
homeassistant_api: true
hassio_api: true
full_access: true
map:
  - type: homeassistant_config
    read_only: false
options:
  cooldown_seconds: 2
schema:
  cooldown_seconds: float
