name: USB NFC Reader
version: "1.5.1"
slug: acr122u_reader
description: Plug-and-play USB NFC reader integration for Home Assistant
url: https://github.com/Flaniel44/ha-usb-nfc
startup: services
boot: auto
init: false
arch:
  - aarch64
homeassistant_api: true
hassio_api: true
full_access: true
map:
  - type: homeassistant_config
    read_only: false
options:
  cooldown_seconds: 2
  removal_poll_interval: 0.15
schema:
  cooldown_seconds: float
  removal_poll_interval: float
